import type {
  ProviderDirectoryData,
  ProviderDirectoryEntry,
} from "@/lib/provider-types";


const demoProviders: ProviderDirectoryEntry[] = [
  {
    dftaId: "DEMO-001",
    programName: "Harbor Community Adult Day Center",
    sponsorName: "Harbor Community Services LLC",
    address: "125 Example Avenue",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11201",
    borough: "Brooklyn",
    phone: "718-555-0101",
    funded: false,
    bin: "",
    bbl: "",
    latitude: 40.694,
    longitude: -73.99,
    npiMatch: {
      npi: "1999000001",
      confidence: "medium",
      score: 60,
      reasons: ["Same ZIP code", "Similar organization name"],
      orgName: "Harbor Community Adult Day Care",
      rawAddress: "127 Example Avenue",
      cleanAddress: "127 EXAMPLE AVE",
      zipCode: "11201",
      phone: "7185550101",
      enumerationDate: "2021-04-12",
    },
    flags: [
      {
        id: "DEMO-001-address",
        label: "data discrepancy",
        severity: "medium",
        title: "Registry and NPPES addresses differ",
        summary:
          "The illustrative registry record and NPPES match list different street numbers.",
        sourceName: "Demonstration data",
        sourceUrl: "#",
        observedAt: null,
        matchConfidence: "medium",
        limitations: "Illustrative only; not a real provider or finding.",
        sourceRecordId: "DEMO-001",
        reportingPeriod: "Illustrative snapshot",
        identityBasis: "Demonstration facility identifier",
        npi: "1999000001",
        address: "125 Example Avenue, Brooklyn, NY 11201",
        valuesCompared: ["125 Example Avenue", "127 Example Avenue"],
        matchRule: "Illustrative address comparison",
        benignExplanations: "A move, stale record, or separate mailing address.",
        recordsNeeded: "Current site-level registration and NPI validation.",
        reviewStatus: "not reviewed",
      },
    ],
    relatedFacilityCount: 1,
  },
  {
    dftaId: "DEMO-002",
    programName: "Harbor Community Social Club",
    sponsorName: "Harbor Community Services LLC",
    address: "410 Sample Street",
    city: "Queens",
    state: "NY",
    zipCode: "11355",
    borough: "Queens",
    phone: "718-555-0101",
    funded: false,
    bin: "",
    bbl: "",
    latitude: 40.75,
    longitude: -73.82,
    npiMatch: {
      npi: null,
      confidence: "unmatched",
      score: 0,
      reasons: [],
      orgName: null,
      rawAddress: null,
      cleanAddress: null,
      zipCode: null,
      phone: null,
      enumerationDate: null,
    },
    flags: [
      {
        id: "DEMO-002-npi",
        label: "data discrepancy",
        severity: "medium",
        title: "No NPPES match found",
        summary:
          "The illustrative facility could not be reconciled to the available NPPES result set.",
        sourceName: "Demonstration data",
        sourceUrl: "#",
        observedAt: null,
        matchConfidence: "ambiguous",
        limitations: "Illustrative only; not a real provider or finding.",
        sourceRecordId: "DEMO-002",
        reportingPeriod: "Illustrative snapshot",
        identityBasis: "Demonstration facility identifier",
        npi: null,
        address: "410 Sample Street, Queens, NY 11355",
        valuesCompared: ["Illustrative registry identity", "No NPPES match"],
        matchRule: "Illustrative identity reconciliation",
        benignExplanations: "A different taxonomy, entity name, or site-level NPI.",
        recordsNeeded: "Current site-level NPI validation.",
        reviewStatus: "not reviewed",
      },
    ],
    relatedFacilityCount: 1,
  },
];

export const demoProviderDirectory: ProviderDirectoryData = {
  providers: demoProviders,
  source: "demo-fallback",
  retrievedAt: new Date(0).toISOString(),
  registryCount: demoProviders.length,
  nppesCount: 1,
  exclusionCount: 0,
};
